// Generated by CoffeeScript 1.7.1
/*
// ==UserScript==
// @name       jnb remove alert
// @version    1.0
// @author     ebith
// @include    https://login.japannetbank.co.jp/wctx/NBCW2101.do
// @grant none
// @noframes
// ==/UserScript==
 */

(function() {
  document.getElementById('seqInfo').remove();

}).call(this);
