// Generated by CoffeeScript 1.7.1
/*
// ==UserScript==
// @name nicovideo watch page fix
// @version 1.3
// @author ebith
// @include http://www.nicovideo.jp/watch/*
// @noframes
// ==/UserScript==
ref: https://greasyfork.org/scripts/452-shinjukuwatch/code
 */

(function() {
  var WIM, main;

  WIM = {};

  require(['watchapp/model/WatchInfoModel'], function(wim) {
    var onReset;
    WIM = wim.getInstance();
    if (WIM.initialized) {
      return main();
    } else {
      onReset = function() {
        return setTimeout((function() {
          return main();
        }), 1000);
      };
      return WIM.addEventListener('reset', onReset);
    }
  });

  main = function() {
    var NPC, css, style, vEC;
    css = '#videoHeaderTagList > .locked:before { content: "🔒"; color: #b5a642;}';
    style = document.createElement('style');
    style.setAttribute('type', 'text/css');
    style.textContent = css;
    document.body.appendChild(style);
    require('watchapp/api/TagAPILoader').prototype.getTags(WIM.v, function(status, data) {
      var tagList;
      tagList = document.getElementById("videoHeaderTagList").getElementsByClassName("videoHeaderTag");
      return data.tags.forEach(function(tag) {
        if (tag.owner_lock === 1) {
          return Array.forEach(tagList, function(elem) {
            if (elem.firstChild.textContent === tag.tag) {
              return elem.classList.add('locked');
            }
          });
        }
      });
    });
    NPC = require('watchapp/model/player/NicoPlayerConnector');
    NPC.onTagDataReceived = function() {};
    NPC.getCommentNicoruCount = function() {
      return 0;
    };
    vEC = require('watchapp/init/VideoExplorerInitializer').videoExplorerController;
    vEC.showMylist = $.proxy(function(id) {
      return location.href = "/mylist/" + id;
    });
    return vEC.searchVideo = $.proxy(function(word, type) {
      return location.href = "/tag/" + (encodeURIComponent(word));
    });
  };

}).call(this);
