// Generated by CoffeeScript 1.7.1
/*
// ==UserScript==
// @name       Steamの年齢確認を自動で進む
// @version    1.0
// @author     ebith
// @include    http://steamcommunity.com/sharedfiles/filedetails/*
// @grant none
// @noframes
// ==/UserScript==
 */

(function() {
  var _ref;

  if ((_ref = document.getElementById('age_gate_btn_continue')) != null) {
    _ref.click();
  }

}).call(this);
